name: 'Invoke-WebRequest-CompositAction'
inputs:
  URL:  # id of input
    description: 'URL'
    required: true
    default: ''
  KEY_VALUE: 
    description: 'URL'
    required: false
    default: 'none'

runs:
  using: "composite"
  steps:
    - name: Invoke-WebRequest
      shell: pwsh
      env: 
         URL: ${{ inputs.URL }}
         KEY_VALUE: ${{ inputs.KEY_VALUE }}
      run: |
          try {
             $response = Invoke-WebRequest -Uri ${{ inputs.URL }} -Method Get
             
             if ($response.StatusCode -lt 300){
                 #Write-Host $response
                 $keyValue= ConvertFrom-Json $response.Content | Select-Object -expand "${{ inputs.KEY_VALUE }}"
                 if ($keyValue -like 'false') {
                    echo $keyValue              
                    exit 1
                }
             }
             else {
                Write-Host $response.StatusCode
                Write-Host $response.StatusDescription
             }
          }
          catch {
             # Write-Host Exception
          }
